# Generated by Django 3.2.1 on 2021-05-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('WA', 'Wayanad'), ('KL', 'Kollam'), ('TS', 'Thrissur'), ('KT', 'Kottayam'), ('TV', 'Trivandrum'), ('ID', 'Idukki'), ('KS', 'Kasaragod'), ('MA', 'Malappuram'), ('PL', 'Palakkad'), ('PT', 'Pathanamthitta'), ('AL', 'Alappuzha'), ('Kz', 'Kozhikode'), ('KN', 'Kannur'), ('ER', 'Ernakulam')], max_length=2)),
                ('phone', models.IntegerField()),
                ('sector', models.CharField(choices=[('gov', 'Government'), ('prv', 'private')], max_length=3)),
                ('covid_beds', models.IntegerField()),
                ('normal_beds', models.IntegerField()),
                ('icu_beds', models.IntegerField()),
                ('ventilator', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('WA', 'Wayanad'), ('KL', 'Kollam'), ('TS', 'Thrissur'), ('KT', 'Kottayam'), ('TV', 'Trivandrum'), ('ID', 'Idukki'), ('KS', 'Kasaragod'), ('MA', 'Malappuram'), ('PL', 'Palakkad'), ('PT', 'Pathanamthitta'), ('AL', 'Alappuzha'), ('Kz', 'Kozhikode'), ('KN', 'Kannur'), ('ER', 'Ernakulam')], max_length=2)),
                ('phone', models.IntegerField()),
                ('aadhar_no', models.IntegerField()),
                ('category', models.CharField(choices=[('cv', 'covid'), ('nc', 'nocovid')], max_length=2)),
                ('status', models.CharField(choices=[('A', 'Admitted'), ('D', 'Discharged'), ('W', 'Waiting')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('N', 'Normal'), ('I', 'ICU'), ('V', 'Ventilator'), ('C', 'Covid')], max_length=2)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.patient')),
            ],
        ),
    ]
