# Generated by Django 3.2.1 on 2021-05-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedallocation',
            name='category',
            field=models.CharField(choices=[('C', 'Covid'), ('N', 'Normal'), ('I', 'ICU'), ('V', 'Ventilator')], max_length=2),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.CharField(choices=[('TS', 'Thrissur'), ('KN', 'Kannur'), ('ID', 'Idukki'), ('MA', 'Malappuram'), ('WA', 'Wayanad'), ('KL', 'Kollam'), ('PT', 'Pathanamthitta'), ('ER', 'Ernakulam'), ('KT', 'Kottayam'), ('Kz', 'Kozhikode'), ('PL', 'Palakkad'), ('AL', 'Alappuzha'), ('TV', 'Trivandrum'), ('KS', 'Kasaragod')], max_length=2),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='category',
            field=models.CharField(choices=[('nc', 'nocovid'), ('cv', 'covid')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.CharField(choices=[('TS', 'Thrissur'), ('KN', 'Kannur'), ('ID', 'Idukki'), ('MA', 'Malappuram'), ('WA', 'Wayanad'), ('KL', 'Kollam'), ('PT', 'Pathanamthitta'), ('ER', 'Ernakulam'), ('KT', 'Kottayam'), ('Kz', 'Kozhikode'), ('PL', 'Palakkad'), ('AL', 'Alappuzha'), ('TV', 'Trivandrum'), ('KS', 'Kasaragod')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
