# Generated by Django 3.2.1 on 2021-05-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_auto_20210507_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.CharField(choices=[('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('Kz', 'Kozhikode'), ('MA', 'Malappuram'), ('PL', 'Palakkad'), ('PT', 'Pathanamthitta'), ('TV', 'Trivandrum'), ('TS', 'Thrissur'), ('WA', 'Wayanad')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='category',
            field=models.CharField(choices=[('cv', 'covid'), ('nc', 'nocovid')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.CharField(choices=[('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('Kz', 'Kozhikode'), ('MA', 'Malappuram'), ('PL', 'Palakkad'), ('PT', 'Pathanamthitta'), ('TV', 'Trivandrum'), ('TS', 'Thrissur'), ('WA', 'Wayanad')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('A', 'Admitted'), ('D', 'Discharged')], max_length=2),
        ),
    ]
